services:
  db:
    image: mysql:8 # o mariadb:10.6
    container_name: django_mysql_db
    env_file: # Credenciales BD MySQL). Deben coincidir con settings.py de Django!
      - ./.env
    ports:
      - "3306:3306" # Expone el puerto por defecto de MySQL (Opcional, útil para herramientas externas)
    volumes:
      # Montar el script de inicialización
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      # Montar el archivo de configuración
      - ./mysql/mysql.ini:/etc/mysql/conf.d/mysql.ini
      # Volumen persistente para los datos de la BD
      - mysql_data:/var/lib/mysql 
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$$MYSQL_USER -p$$MYSQL_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    
  web:
    build: . 
    container_name: django_web_app
    # El script entrypoint.sh se ejecuta automaticamente
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app # Montaje de Código (Host al Contenedor)
      - static_volume:/usr/src/app/static # Archivos estáticos      
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy # Espera hasta que la BD esté marcada como "healthy"
            
volumes: # Volumenes globales
  mysql_data:
  static_volume: 
